// techdata.js — GENERATED from data/techs.json (round-50 tech tree, 66 nodes).
// PREVIEW-ONLY: the real desktop app gets this graph (with x/y/perks) from the bit-exact
// engine via the `meta` Tauri command; this copy exists solely so the browser mock can render
// the same tech-tree tab. Regenerate if data/techs.json changes (it only changes per round).
export const TECHS = [
  { key: "tech_10_11", name: "WaveHack's Expertise", x: 10, y: 11, perks: { "boat_capacity": 3, "construction_platinum_cost": -5, "construction_lumber_cost": -10 }, requires: ["tech_9_13", "tech_11_13"] },
  { key: "tech_10_15", name: "Battle Commanders", x: 10, y: 15, perks: { "casualties": -7.5 }, requires: ["tech_9_13", "tech_11_17"] },
  { key: "tech_10_19", name: "Military Culture", x: 10, y: 19, perks: { "prestige_gains": 7.5 }, requires: ["tech_9_17", "tech_11_17", "tech_11_21"] },
  { key: "tech_10_3", name: "Sleeper Agents", x: 10, y: 3, perks: { "max_population": 1, "spy_losses": -7.5 }, requires: ["tech_9_1", "tech_11_5"] },
  { key: "tech_10_7", name: "Midas's Fountain", x: 10, y: 7, perks: { "platinum_production": 4 }, requires: ["tech_8_7"] },
  { key: "tech_11_1", name: "Industrial Machinery", x: 11, y: 1, perks: { "lumber_production": 5, "ore_production": 5 }, requires: ["tech_9_1", "tech_13_1"] },
  { key: "tech_11_13", name: "Field Surgery", x: 11, y: 13, perks: { "casualties": -7.5, "max_population": 0.75 }, requires: ["tech_10_11"] },
  { key: "tech_11_17", name: "Carpenter's Knowhow", x: 11, y: 17, perks: { "construction_platinum_cost": -5 }, requires: ["tech_10_15", "tech_12_15", "tech_10_19", "tech_12_19"] },
  { key: "tech_11_21", name: "Battle Tactics", x: 11, y: 21, perks: { "casualties": -5 }, requires: [] },
  { key: "tech_11_5", name: "Master of Efficiency", x: 11, y: 5, perks: { "military_cost": -1.75 }, requires: ["tech_10_3", "tech_12_3"] },
  { key: "tech_11_9", name: "Avatar of Ares", x: 11, y: 9, perks: { "offense": 2.5, "wizard_power": 7.5 }, requires: ["tech_12_11"] },
  { key: "tech_12_11", name: "Surveyor's Sense", x: 12, y: 11, perks: { "rezone_cost": -12.5 }, requires: ["tech_11_9", "tech_13_13"] },
  { key: "tech_12_15", name: "Bunk Beds", x: 12, y: 15, perks: { "barracks_housing": 2 }, requires: ["tech_13_13", "tech_11_17"] },
  { key: "tech_12_19", name: "Surveyor's Insight", x: 12, y: 19, perks: { "rezone_cost": -7.5 }, requires: ["tech_11_17", "tech_13_17", "tech_11_21"] },
  { key: "tech_12_3", name: "Explorer's Instinct", x: 12, y: 3, perks: { "construction_platinum_cost": -5, "explore_platinum_cost": -2.5 }, requires: ["tech_13_1", "tech_11_5"] },
  { key: "tech_12_7", name: "Menace", x: 12, y: 7, perks: { "mana_production_raw": 2, "wartime_mana_production_raw": 1.5 }, requires: ["tech_13_5"] },
  { key: "tech_13_1", name: "Siege Weaponry", x: 13, y: 1, perks: { "wonder_damage": 20, "raid_attack_damage": 50 }, requires: ["tech_11_1", "tech_15_1", "tech_12_3"] },
  { key: "tech_13_13", name: "Ares' Favor", x: 13, y: 13, perks: { "offense": 2.5 }, requires: ["tech_12_11", "tech_12_15", "tech_14_15"] },
  { key: "tech_13_17", name: "Ancestral Knowledge", x: 13, y: 17, perks: { "racial_spell_cost": -25 }, requires: ["tech_14_15", "tech_12_19"] },
  { key: "tech_13_5", name: "Pastoral Planner", x: 13, y: 5, perks: { "max_population": 1.5 }, requires: ["tech_14_3", "tech_12_7"] },
  { key: "tech_13_9", name: "Master of Discipline", x: 13, y: 9, perks: { "military_cost": -1.75 }, requires: ["tech_15_9", "tech_14_11"] },
  { key: "tech_14_11", name: "Visionary Expansionist", x: 14, y: 11, perks: { "max_population": 1, "population_growth": 15 }, requires: ["tech_13_9", "tech_15_13"] },
  { key: "tech_14_15", name: "Public Baths", x: 14, y: 15, perks: { "population_growth": 30 }, requires: ["tech_13_13", "tech_15_13", "tech_13_17"] },
  { key: "tech_14_3", name: "Wizard Nexus", x: 14, y: 3, perks: { "wizard_strength_recovery": 1 }, requires: ["tech_15_1", "tech_16_3", "tech_13_5"] },
  { key: "tech_14_7", name: "Architect's Flourish", x: 14, y: 7, perks: { "construction_platinum_cost": -10 }, requires: ["tech_15_5", "tech_16_7"] },
  { key: "tech_15_1", name: "Sneaky Spies", x: 15, y: 1, perks: { "theft_gains": 10, "spy_losses": -15 }, requires: ["tech_13_1", "tech_17_1", "tech_14_3"] },
  { key: "tech_15_13", name: "Rations", x: 15, y: 13, perks: { "extra_barren_max_population": 2, "food_consumption": -2.5 }, requires: ["tech_14_11", "tech_16_11", "tech_14_15"] },
  { key: "tech_15_5", name: "Explorer's Guile", x: 15, y: 5, perks: { "explore_platinum_cost": -7.5, "explore_draftee_cost": -2 }, requires: ["tech_14_7"] },
  { key: "tech_15_9", name: "Dark Artistry", x: 15, y: 9, perks: { "spy_strength_recovery": 1, "wizard_strength_recovery": 1 }, requires: ["tech_13_9", "tech_17_9"] },
  { key: "tech_16_11", name: "Survivalist Mentality", x: 16, y: 11, perks: { "casualties": -5, "prestige_gains": 7.5 }, requires: ["tech_17_9", "tech_15_13"] },
  { key: "tech_16_3", name: "Preservationist", x: 16, y: 3, perks: { "food_decay": -15, "lumber_decay": -15, "mana_decay": -15 }, requires: ["tech_14_3", "tech_18_3"] },
  { key: "tech_16_7", name: "Night Watch", x: 16, y: 7, perks: { "enemy_assassinate_draftees_damage": -25, "enemy_assassinate_wizards_damage": -25, "enemy_disband_spies_damage": -25 }, requires: ["tech_17_5", "tech_18_7"] },
  { key: "tech_17_1", name: "Arcane Bloodlines", x: 17, y: 1, perks: { "wizard_cost": -20 }, requires: ["tech_15_1", "tech_19_1"] },
  { key: "tech_17_5", name: "Deep Pockets", x: 17, y: 5, perks: { "theft_gains": 15 }, requires: ["tech_18_3", "tech_16_7"] },
  { key: "tech_17_9", name: "Ross' Benevolence", x: 17, y: 9, perks: { "guard_tax": -1 }, requires: ["tech_18_7", "tech_15_9", "tech_16_11"] },
  { key: "tech_18_3", name: "Explorer's Intuition", x: 18, y: 3, perks: { "explore_platinum_cost": -2.5, "explore_draftee_cost": -1 }, requires: ["tech_19_1", "tech_16_3", "tech_20_3", "tech_17_5"] },
  { key: "tech_18_7", name: "Shadow Academy", x: 18, y: 7, perks: { "archmage_cost": -20, "assassin_cost": -20 }, requires: ["tech_19_5", "tech_16_7", "tech_17_9"] },
  { key: "tech_19_1", name: "Frugal Foragers", x: 19, y: 1, perks: { "food_consumption": -2.5 }, requires: ["tech_17_1", "tech_21_1", "tech_18_3"] },
  { key: "tech_19_5", name: "Mana Pools", x: 19, y: 5, perks: { "spell_cost": -10 }, requires: ["tech_20_3", "tech_18_7"] },
  { key: "tech_1_1", name: "Granaries", x: 1, y: 1, perks: { "food_production": 2.5 }, requires: [] },
  { key: "tech_20_3", name: "Architect's Touch", x: 20, y: 3, perks: { "construction_platinum_cost": -2.5 }, requires: ["tech_21_1", "tech_18_3", "tech_19_5"] },
  { key: "tech_21_1", name: "Reforestation", x: 21, y: 1, perks: { "construction_lumber_cost": -10 }, requires: [] },
  { key: "tech_2_3", name: "Surplus Management", x: 2, y: 3, perks: { "food_decay": -10, "lumber_decay": -10, "mana_decay": -10 }, requires: ["tech_1_1", "tech_3_5", "tech_4_3"] },
  { key: "tech_3_1", name: "Planar Emissaries", x: 3, y: 1, perks: { "mana_production": 5 }, requires: ["tech_1_1", "tech_5_1", "tech_4_3"] },
  { key: "tech_3_5", name: "Miner's Spirit", x: 3, y: 5, perks: { "ore_production": 5 }, requires: ["tech_2_3", "tech_4_7"] },
  { key: "tech_4_3", name: "Banker's Friend", x: 4, y: 3, perks: { "exchange_bonus": 15 }, requires: ["tech_3_1", "tech_2_3", "tech_5_5", "tech_6_3"] },
  { key: "tech_4_7", name: "Shipwright's Ingenuity", x: 4, y: 7, perks: { "boat_production": 12.5 }, requires: ["tech_3_5", "tech_6_7", "tech_5_9"] },
  { key: "tech_5_1", name: "Green Thumb", x: 5, y: 1, perks: { "lumber_production": 5 }, requires: ["tech_3_1", "tech_7_1"] },
  { key: "tech_5_5", name: "Ancient Mines", x: 5, y: 5, perks: { "gem_production": 2.5 }, requires: ["tech_4_3", "tech_6_7"] },
  { key: "tech_5_9", name: "Weather Manipulation", x: 5, y: 9, perks: { "enemy_lightning_bolt_damage": -12.5, "food_production": 2.5 }, requires: ["tech_4_7", "tech_7_9", "tech_6_11"] },
  { key: "tech_6_11", name: "Urban Planner", x: 6, y: 11, perks: { "max_population": 1.5 }, requires: ["tech_5_9", "tech_7_13"] },
  { key: "tech_6_3", name: "Prefabrication", x: 6, y: 3, perks: { "construction_platinum_cost": -10 }, requires: ["tech_4_3", "tech_8_3"] },
  { key: "tech_6_7", name: "Trick of the Light", x: 6, y: 7, perks: { "improved_fools_gold": 1 }, requires: ["tech_5_5", "tech_4_7", "tech_8_7"] },
  { key: "tech_7_1", name: "Aquaponics", x: 7, y: 1, perks: { "food_production": 7.5, "enemy_burning_duration": -4 }, requires: ["tech_5_1", "tech_9_1", "tech_8_3"] },
  { key: "tech_7_13", name: "Reinforced Bulwarks", x: 7, y: 13, perks: { "invest_bonus_harbor": 30, "invest_bonus_spires": 30 }, requires: ["tech_6_11", "tech_8_11", "tech_8_15"] },
  { key: "tech_7_5", name: "Urg Smash Technique", x: 7, y: 5, perks: { "destruction_discount": 100, "lumber_production": 7.5 }, requires: ["tech_9_5"] },
  { key: "tech_7_9", name: "Lumberjack's Devotion", x: 7, y: 9, perks: { "construction_lumber_cost": -20, "lumber_decay": -20 }, requires: ["tech_5_9", "tech_9_9"] },
  { key: "tech_8_11", name: "Jeweller's Delight", x: 8, y: 11, perks: { "gem_production": 2.5, "self_spell_cost": -5 }, requires: ["tech_9_9", "tech_7_13"] },
  { key: "tech_8_15", name: "Tributary System", x: 8, y: 15, perks: { "food_production_prestige": 60 }, requires: ["tech_7_13", "tech_9_13", "tech_9_17"] },
  { key: "tech_8_3", name: "Miser's Grasp", x: 8, y: 3, perks: { "spy_power_defense": 10, "theft_losses": -25 }, requires: ["tech_7_1", "tech_6_3"] },
  { key: "tech_8_7", name: "Opulence", x: 8, y: 7, perks: { "gem_production": 2.5, "ore_production": 7.5 }, requires: ["tech_6_7", "tech_10_7"] },
  { key: "tech_9_1", name: "Midas's Bargain", x: 9, y: 1, perks: { "platinum_production": 2 }, requires: ["tech_7_1", "tech_11_1", "tech_10_3"] },
  { key: "tech_9_13", name: "Spy Network", x: 9, y: 13, perks: { "spy_strength_recovery": 1 }, requires: ["tech_10_11", "tech_8_15", "tech_10_15"] },
  { key: "tech_9_17", name: "Centralized Intelligence", x: 9, y: 17, perks: { "spy_cost": -20 }, requires: ["tech_8_15", "tech_10_19"] },
  { key: "tech_9_5", name: "Dark Pact", x: 9, y: 5, perks: { "mana_production": 10, "wizard_power": 5 }, requires: ["tech_7_5", "tech_8_3"] },
  { key: "tech_9_9", name: "Master of Resources", x: 9, y: 9, perks: { "military_cost": -1.75 }, requires: ["tech_7_9", "tech_8_11"] },
];
